In [1]:
import numpy as np
from keras.models import load_model
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

import pickle

In [2]:
model = load_model("models\\test_4_sort(6).h5")

In [3]:
with open('files\\4_sort.pickle', 'rb') as file:
    pre_files_sort = pickle.load(file)

In [4]:
maxWord = 15
max_text_len = 40
tokenizer = Tokenizer(num_words=maxWord, lower = True, split = ' ', char_level=False)
tokenizer.fit_on_texts(pre_files_sort)
dist = list(tokenizer.word_counts.items())
data = tokenizer.texts_to_sequences(pre_files_sort)
data_pad = pad_sequences(data,maxlen = max_text_len)

In [5]:
def test_model(text,max_text_len = max_text_len,model=model):
    test_text = text.lower()
    data_test = tokenizer.texts_to_sequences([test_text])
    data_pad_test = pad_sequences(data_test, maxlen = max_text_len)
    res = model.predict(data_pad_test)
    return res, np.argmax(res)

In [6]:
test_model("""def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]""")

(array([[0.84076196, 0.02764904, 0.05954951, 0.07203955]], dtype=float32), 0)

In [10]:
test_model("""
    def quicksort(arr):
        if len(arr) <= 1:
            return arr
        else:
            pivot = arr[0]
            less = [x for x in arr[1:] if x <= pivot]
            greater = [x for x in arr[1:] if x > pivot]
            return quicksort(less) + [pivot] + quicksort(greater)
            """)

(array([[0.16648537, 0.5147089 , 0.14682344, 0.17198232]], dtype=float32), 1)

In [11]:
test_model("""def selection_sort(arr):        
    for i in range(len(arr)):
        minimum = i
        for j in range(i + 1, len(arr)):
            if arr[j] < arr[minimum]:
                minimum = j
        arr[minimum], arr[i] = arr[i], arr[minimum]
    return arr""")

(array([[0.08747803, 0.11899498, 0.69053763, 0.10298934]], dtype=float32), 2)

In [12]:
test_model("""import operator
def merge_sort(L, compare=operator.lt):
    if len(L) < 2:
        return L[:]
    else:
        middle = int(len(L) / 2)
        left = merge_sort(L[:middle], compare)
        right = merge_sort(L[middle:], compare)
        return merge(left, right, compare)
        
        def merge(left, right, compare):
    result = []
    i, j = 0, 0
    while i < len(left) and j < len(right):
        if compare(left[i], right[j]):
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1
    while i < len(left):
        result.append(left[i])
        i += 1
    while j < len(right):
        result.append(right[j])
        j += 1
    return result""")

(array([[0.12176348, 0.23194884, 0.09657823, 0.54970944]], dtype=float32), 3)