In [1]:
import numpy as np
from keras.models import load_model
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

import pickle

In [2]:
model = load_model("models\\test_5_sort.h5")

In [3]:
with open('files\\5_sort.pickle', 'rb') as file:
    pre_files_sort = pickle.load(file)

In [4]:
maxWord = 25
max_text_len = 400
tokenizer = Tokenizer(num_words=maxWord, lower = True, split = ' ', char_level=False)
tokenizer.fit_on_texts(pre_files_sort)
# dist = list(tokenizer.word_counts.items())
# data = tokenizer.texts_to_sequences(pre_files_sort)
# data_pad = pad_sequences(data,maxlen = max_text_len)

In [5]:
def test_model(text,max_text_len = max_text_len,model=model):
    test_text = text.lower()
    data_test = tokenizer.texts_to_sequences([test_text])
    data_pad_test = pad_sequences(data_test, maxlen = max_text_len)
    res = model.predict(data_pad_test)
    return res, np.argmax(res)

In [6]:
test_model("""
    def bubble_sort(arr):
        n = len(arr)
        for i in range(n):
            for j in range(0, n - i - 1):
                if arr[j] > arr[j + 1]:
                    arr[j], arr[j + 1] = arr[j + 1], arr[j]
            """)

(array([[0.3395725 , 0.10672836, 0.23338915, 0.21910888, 0.10120106]],
       dtype=float32),
 0)

In [7]:
test_model("""
def QuickSort(A):
    if len(A) <= 1:
        return A
    else:
        q = random.choice(A)
        L = []
        M = []
        R = []
        for elem in A:
            if elem < q:
                L.append(elem) 
            elif elem > q: 
                R.append(elem) 
            else: 
                M.append(elem)
        return QuickSort(L) + M + QuickSort(R)
            """)

(array([[0.22572461, 0.26119363, 0.25871518, 0.06886439, 0.18550217]],
       dtype=float32),
 1)

In [8]:
test_model("""
    def selection_sort(arr):        
        for i in range(len(arr)):
            minimum = i
            for j in range(i + 1, len(arr)):
                if arr[j] < arr[minimum]:
                    minimum = j
            arr[minimum], arr[i] = arr[i], arr[minimum]
        return arr
            """)

(array([[0.2711959 , 0.18320379, 0.30227724, 0.09464854, 0.14867456]],
       dtype=float32),
 2)

In [9]:
test_model("""
    import operator
    def merge_sort(L, compare=operator.lt):
        if len(L) < 2:
            return L[:]
        else:
            middle = int(len(L) / 2)
            left = merge_sort(L[:middle], compare)
            right = merge_sort(L[middle:], compare)
            return merge(left, right, compare)

            def merge(left, right, compare):
        result = []
        i, j = 0, 0
        while i < len(left) and j < len(right):
            if compare(left[i], right[j]):
                result.append(left[i])
                i += 1
            else:
                result.append(right[j])
                j += 1
        while i < len(left):
            result.append(left[i])
            i += 1
        while j < len(right):
            result.append(right[j])
            j += 1
        return result
            """)

(array([[0.1648672 , 0.04581341, 0.15210123, 0.5408546 , 0.0963636 ]],
       dtype=float32),
 3)

In [10]:
test_model("""
def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1
    
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]

    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def quicksort(arr, low=0, high=None):
    if high is None:
        high = len(arr) - 1

    if low < high:
        pivot_index = partition(arr, low, high)

        quicksort(arr, low, pivot_index - 1)
        quicksort(arr, pivot_index + 1, high)

    return arr

    """)

(array([[0.21668047, 0.28920454, 0.23970933, 0.04386024, 0.21054535]],
       dtype=float32),
 1)

In [11]:
test_model("""def selection_sort(arr):        
    for i in range(len(arr)):
        minimum = i
        for j in range(i + 1, len(arr)):
            if arr[j] < arr[minimum]:
                minimum = j
        arr[minimum], arr[i] = arr[i], arr[minimum]
    return arr""")

(array([[0.2711959 , 0.18320379, 0.30227724, 0.09464854, 0.14867456]],
       dtype=float32),
 2)

In [12]:
test_model("""def quicksort(arr):
        if len(arr) <= 1:
            return arr
        else:
            pivot = arr[0]
            less = [x for x in arr[1:] if x <= pivot]
            greater = [x for x in arr[1:] if x > pivot]
            return quicksort(less) + [pivot] + quicksort(greater)
            """)

(array([[0.10240275, 0.47731513, 0.1291845 , 0.03136699, 0.25973064]],
       dtype=float32),
 1)

In [15]:
test_model("""import operator
def mergeSort(alist):
    print("Splitting ",alist)
    if len(alist)>1:
        mid = len(alist)//2
        lefthalf = alist[:mid]
        righthalf = alist[mid:]

        mergeSort(lefthalf)
        mergeSort(righthalf)

        i=0
        j=0
        k=0
        while i<len(lefthalf) and j<len(righthalf):
            if lefthalf[i]<righthalf[j]:
                alist[k]=lefthalf[i]
                i=i+1
            else:
                alist[k]=righthalf[j]
                j=j+1
            k=k+1

        while i<len(lefthalf):
            alist[k]=lefthalf[i]
            i=i+1
            k=k+1

        while j<len(righthalf):
            alist[k]=righthalf[j]
            j=j+1
            k=k+1
            """)

(array([[0.17099245, 0.04577858, 0.15389284, 0.5365837 , 0.09275237]],
       dtype=float32),
 3)

In [14]:
test_model("""
def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1
    
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]

    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def quicksort(arr, low=0, high=None):
    if high is None:
        high = len(arr) - 1

    if low < high:
        pivot_index = partition(arr, low, high)

        quicksort(arr, low, pivot_index - 1)
        quicksort(arr, pivot_index + 1, high)

    return arr

    """)

(array([[0.21668047, 0.28920454, 0.23970933, 0.04386024, 0.21054535]],
       dtype=float32),
 1)

# Feedback

In [13]:
alg_dict = {'sort': ['bubble_sort', 'quick_sort','selection_sort', 'merge_sort', 'insertion_sort'], 'find': ['binary_search']}
alg_dict['sort'] in alg_dict

TypeError: unhashable type: 'list'

In [10]:
def feedback():
    alg_dict = {'sort': ['bubble_sort', 'quick_sort','selection_sort', 'merge_sort', 'insertion_sort'], 'find': ['binary_search']}
    alg_type = str(input())
    if alg_type not in alg_dict: 
        raise ValueError("Нет такого типа")
    alg_name = str(input())
    if alg_type[alg_name] not in alg_dict:
        raise ValueError("Нет такого алгоритма")

sorr


ValueError: Нет такого типа